# Generated by Django 5.0 on 2023-12-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_reservationmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationmodel',
            name='reservation_date',
            field=models.CharField(max_length=15),
        ),
    ]
